/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.10.1.112 */
/* Module Version: 1.2 */
/* Sun Mar 25 17:08:19 2018 */

/* parameterized module instance */
I2C_EFB_WB __ (.wb_clk_i( ), .wb_rst_i( ), .wb_cyc_i( ), .wb_stb_i( ), 
    .wb_we_i( ), .wb_adr_i( ), .wb_dat_i( ), .wb_dat_o( ), .wb_ack_o( ), 
    .i2c1_scl( ), .i2c1_sda( ), .i2c1_irqo( ), .i2c2_scl( ), 
    .i2c2_sda( ), .i2c2_irqo( ));
