/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.10.1.112 */
/* Module Version: 3.5 */
/* Sun Apr 15 14:00:22 2018 */

/* parameterized module instance */
multiplier __ (.DataA( ), .DataB( ), .Result( ));
