//Verilog testbench template generated by SCUBA Diamond (64-bit) 3.10.1.112
`timescale 1 ns / 1 ps
module tb;
    reg [15:0] DataA = 16'b0;
    reg [15:0] DataB = 16'b0;
    reg Cin = 0;
    wire [15:0] Result;
    wire Overflow;

    integer i0 = 0, i1 = 0, i2 = 0, i3 = 0, i4 = 0;

    GSR GSR_INST (.GSR(1'b1));
    PUR PUR_INST (.PUR(1'b1));

    adder u1 (.DataA(DataA), .DataB(DataB), .Cin(Cin), .Result(Result), 
        .Overflow(Overflow)
    );

    initial
    begin
       DataA <= 0;
      for (i1 = 0; i1 < 200; i1 = i1 + 1) begin
        #10;
         DataA <= DataA + 1'b1;
      end
    end
    initial
    begin
       DataB <= 0;
      for (i2 = 0; i2 < 200; i2 = i2 + 1) begin
        #10;
         DataB <= DataB + 1'b1;
      end
    end
    initial
    begin
       Cin <= 1'b0;
      for (i3 = 0; i3 < 100; i3 = i3 + 1) begin
        #10;
      end
       Cin <= 1'b1;
    end
endmodule