/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.10.1.112 */
/* Module Version: 3.5 */
/* Sun Apr 15 16:01:47 2018 */

/* parameterized module instance */
adder __ (.DataA( ), .DataB( ), .Cin( ), .Result( ), .Overflow( ));
